services:
  - type: web
    name: sportox-backend
    runtime: image
    repo: https://github.com/TU_USUARIO/TU_REPOSITORIO
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: API_GLOBAL_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: AUTO_REFRESH_HOURS
        value: "24"
      - key: REQUEST_TIMEOUT
        value: "30"
